LMRA/urls.py
from django.urls import path

from . import views
from .views import lmra

app_name = 'LMRA'
urlpatterns = [
    #create LMRA
    path('create/', views.create_LMRA, name='create'),
    #home page
    path('', views.homepage, name='home'),
    #View LMRAs
    path('lmras/', views.lmras, name='lmras'),
    #View detail for single LMRA
    path('lmra/<int:pk>/', lmra.as_view(), name='lmra'),

]

safety_app/urls.py
from django.contrib import admin
from django.urls import path, include
from LMRA.views import homepage
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage, name='home'),
    path('lmra/', include('LMRA.urls')),
    path('users/', include('users.urls')),
    path('unsafe/', include('unsafe_condition.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

unsafe_condition/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'unsafe_condition'
urlpatterns = [
    path('create/', views.report_unsafe_condition, name='create'),
    path('success/', views.unsafe_condition_success, name='success'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

LMRA/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here.
class LMRA(models.Model):
    """Basic LMRA model"""
    date_added = models.DateField(auto_now_add=True)
    location = models.CharField(max_length=50)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.location
    
class Hazard(models.Model):
    """basic hazard model"""
    hazard = models.CharField(max_length=50)
    description = models.TextField()
    likelihood = models.PositiveIntegerField(
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1),
        ]
    )
    severity = models.PositiveIntegerField(
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1),
        ]
    )
    lmra = models.ForeignKey(LMRA, on_delete=models.CASCADE)

    def __str__(self):
        return self.hazard

unsafe_condition/models.py
from django.db import models

# Create your models here.

class UnsafeCondition(models.Model):
    description = models.TextField()
    date_reported = models.DateTimeField(auto_now_add=True)
    location = models.CharField(max_length=100)
    photo = models.ImageField(upload_to='unsafe_condition_photos/', null=True, blank=True)
    
    def __str__(self):
        return f'{self.description[:20]}... at {self.location}'

users/models.py
from django.db import models

# Create your models here.

LMRA/forms.py
from django import forms
from .models import LMRA, Hazard

class LMRAForm(forms.ModelForm):
    class Meta:
        model = LMRA
        fields = ['location']

class HazardForm(forms.ModelForm):
    class Meta:
        model = Hazard
        fields = ['hazard', 'description', 'likelihood', 'severity']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 3}),
            'likelihood': forms.NumberInput(attrs={'min': 1, 'max': 5}),
            'severity': forms.NumberInput(attrs={'min': 1, 'max': 5}),
        }
    likelihood = forms.IntegerField(min_value=1, max_value=5)
    severity = forms.IntegerField(min_value=1, max_value=5)


HazardFormSet = forms.inlineformset_factory(LMRA, Hazard, form=HazardForm, extra=0, can_delete=False)

unsafe_condition/forms.py
from django import forms
from .models import UnsafeCondition

class UnsafeConditionForm(forms.ModelForm):
    class Meta:
        model = UnsafeCondition
        fields = ['location', 'description', 'photo']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 3}),
            'photo': forms.FileInput(),
        }

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUserCreationForm(UserCreationForm):
        email = forms.EmailField(label='Email address')
        first_name = forms.CharField(max_length=30, required=True, help_text='Required.')

        class Meta:
            model = User
            fields = ('email', 'first_name', 'password1', 'password2')
        
        def save(self, commit=True):
            user = super().save(commit=False)
            user.username = self.cleaned_data['email']
            if commit:
                user.save()
            return user

LMRA/views.py
from django.shortcuts import render, redirect
from django.views.generic.detail import DetailView
from .models import LMRA, Hazard
from .forms import LMRAForm, HazardFormSet
from django.contrib.auth.decorators import login_required

# Create your views here.

#LMRA Creation
@login_required
def create_LMRA(request):
    """Create LMRA with linked hazar forms"""
    if request.method == 'POST':
        lmra_form = LMRAForm(data=request.POST)
        hazard_formset = HazardFormSet(data=request.POST)

        if lmra_form.is_valid() and hazard_formset.is_valid():
            lmra = lmra_form.save(commit=False)
            lmra.owner = request.user
            lmra.save()

            for form in hazard_formset:
                hazard = form.save(commit=False)
                hazard.lmra = lmra
                hazard.save()
            return redirect('/')
    else:
        lmra_form = LMRAForm()
        hazard_formset = HazardFormSet()
    
    context = {'lmra_form': lmra_form, 'hazard_formset': hazard_formset}
    return render(request, 'LMRA/create_LMRA.html', context)
@login_required
def homepage(request):
    return render(request, 'LMRA/home.html')


#View to see LMRA's
def lmras(request):
    """Shows all LMRA's"""
    lmras = LMRA.objects.order_by('date_added')
    context = {'lmras': lmras }
    return render(request, 'LMRA/lmras.html', context)

class lmra(DetailView):
    """Show single LMRA"""
    model = LMRA
    template_name = 'LMRA/lmra.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['hazards'] = self.object.hazard_set.all()
        return context

unsafe_condition/views.py
from django.shortcuts import render, redirect
from .forms import UnsafeConditionForm

# Create your views here.

from django.shortcuts import render, redirect
from .forms import UnsafeConditionForm

def report_unsafe_condition(request):
    """View for reporting an unsafe condition."""
    if request.method == 'POST':
        form = UnsafeConditionForm(request.POST, request.FILES)
        if form.is_valid():
            # Save the form data to the database
            unsafe_condition = form.save(commit=False)
            unsafe_condition.save()
            form.save_m2m()
            return redirect('home')
    else:
        form = UnsafeConditionForm()

    context = {'form': form}
    return render(request, 'unsafe_condition/report_unsafe_condition.html', context)

def unsafe_condition_success(request):
    """View for displaying the success message after reporting an unsafe condition."""
    return render(request, 'LMRA:home')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
#from django.contrib.auth.forms import UserCreationForm
from .forms import CustomUserCreationForm


# Create your views here.

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = CustomUserCreationForm()
    else:
        # Process completed form.
        form = CustomUserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('LMRA:home')
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

LMRA/templates/LMRA/base.html
{% load bootstrap4 %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
        shrink-to-fit=no">
    <title>JDEsa</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'home' %}">JDEsa</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                {% comment %} <li class="nav-item">
                    <a class="nav-link" href="{% url 'home'%}"> Home</a>
                </li> {% endcomment %}
               {% comment %}
                 <li class="nav-item">
                     <a class="nav-link" href="{% url 'LMRA:create'%}">Create LMRA</a>
                 </li>
               {% endcomment %}
                {% comment %} <li class="nav-item">
                    <a class="nav-link" href="{% url 'LMRA:lmras'%}">LMRA's</a>
                </li> {% endcomment %}
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text">Hello, {{ user.username }}.</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                    </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login'%}">Log in</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register'%}">Register</a>
                </li>
                {% endif %}
                {% if user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">admin</a>
                {% endif %}


            
                
            </ul>
        </div>
    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
</body>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</html>

LMRA/templates/LMRA/create_LMRA.html
{% extends "LMRA/base.html" %}
{% load bootstrap4 %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Create LMRA</h1>
            <hr>
            <form method="post" class="form">
                {% csrf_token %}
                {% bootstrap_form lmra_form %}
                <div id="hazards">
                    {{ hazard_formset.management_form }}
                    {% for hazard_form in hazard_formset %}
                        <div class="hazard-form mb-3">
                            <div class="card">
                                <div class="card-header">
                                    <h5 class="card-title">Hazard {{ forloop.counter }}</h5>
                                </div>
                                <div class="card-body">
                                    {% bootstrap_form hazard_form %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

                <div class="form-group">
                    <button id="add-hazard" type="button" class="btn btn-primary">Add Hazard</button>
                    <button type="submit" class="btn btn-success">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    console.log("JavaScript code is running!");

    window.addEventListener('DOMContentLoaded', () => {
        const addHazardButton = document.getElementById('add-hazard');
        const hazardsDiv = document.getElementById('hazards');
        const formCountInput = document.querySelector('#id_hazard_set-TOTAL_FORMS');
        const initialFormCount = document.querySelectorAll('.hazard-form').length;
        formCountInput.value = initialFormCount;

        addHazardButton.addEventListener('click', (event) => {
            const emptyForm = `{% bootstrap_form hazard_formset.empty_form %}`;
            const newForm = `
                <div class="hazard-form mb-3">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="card-title">Hazard ${document.querySelectorAll('.hazard-form').length + 1}</h5>
                        </div>
                        <div class="card-body">
                            ${emptyForm.replace(/__prefix__/g, document.querySelectorAll('.hazard-form').length)}
                        </div>
                    </div>
                </div>
            `;
            const formCount = document.querySelectorAll('.hazard-form').length;
            hazardsDiv.insertAdjacentHTML('beforeend', newForm);
            formCountInput.value = formCount + 1;
        });
    });
</script>
{% endblock %}

LMRA/templates/LMRA/home.html
{% extends "LMRA/base.html" %}
{% load static %}
{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3">Work safe, or don't work at all.</h1>
        <p class="lead">
            A portal for the submission of LMRA's and Unsafe conditions.
        </p>
        {% if user.is_authenticated %}
            <a class="btn btn-lg btn-primary" href="{% url 'LMRA:create' %}"
            role="button">Create LMRA &raquo;</a>
            <a class="btn btn-lg btn-danger" href="{% url 'unsafe_condition:create' %}"
            role="button">Report Unsafe Condition &raquo;</a>
        {% else %}
            <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
            role="button">Register &raquo;</a>

        {% endif %}
    </div>
{% endblock page_header %}
{% block content %}
    <img src="{% static 'img/logo.png' %}" alt="My Logo" class="logo-img">
{% endblock content %}

LMRA/templates/LMRA/lmra.html
{% extends "LMRA/base.html" %}

{% block content %}

<h1>{{ object.location }}</h1>
<h3>{{ object.date_added }}</h3>
    {% for hazard in hazards %}
        <li>{{ hazard.hazard }}</li>
    {% endfor %}

{% endblock content %}

LMRA/templates/LMRA/lmras.html
{% extends "LMRA/base.html" %}

{% block page_header %}
    <h1>LMRA's</h1>
{% endblock page_header %}

{% block content %}
    <ul>
        {% for lmra in lmras %}
            <div class="card mb-3">
                <h4 class="card-header">
                    <a href="{% url 'LMRA:lmra' lmra.id %}">{{ lmra }}</a>
                </h4>
                <div class="card-body">
                    {{ lmra.date_added }}
                </div>
            </div>
        {% empty %}
            <li>No LMRA's have been submitted yet.</li>
        {% endfor %}
    </ul>

    {% endblock content %}

unsafe_condition/templates/unsafe_condition/report_unsafe_condition.html
{% extends "LMRA/base.html" %}
{% load bootstrap4%}

{% block page_header %}
    <h1>Report an Unsafe Condition</h1>
{% endblock page_header %}

{% block content %}
    <form method="post" class="form" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" class="btn btn-success" disabled >Submit /* feature currently disabled */</button>
        {% endbuttons %}
    </form>
{% endblock content%}

unsafe_condition/templates/unsafe_condition/unsafe_condition_success.html
{% extends "LMRA/base.html" %}